---
kind: Service
apiVersion: v1
metadata:
  name: grainger-di-demo-internal
spec:
  selector:
    app: grainger-di-demo-internal
  ports:
    - name: "http"
      protocol: TCP
      port: 80
      targetPort: 80
      
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grainger-di-demo-internal-deployment
  labels:
    app: grainger-di-demo-internal
{{- if or (eq .cluster_subdomain ".preview-internal") (eq .cluster_subdomain ".nonprod-internal") }}
    version: {{ .tag }}
  annotations:
    graingercloud.com/skipValidations:  securityScan {{ end }}
spec:
  replicas: 3
  selector:
    matchLabels:
      app: grainger-di-demo-internal
  template:
    metadata:
      labels:
        app: grainger-di-demo-internal
        app.kubernetes.io/name: grainger-di-demo-internal
        app.kubernetes.io/version: {{ .tag }}
{{- if or (eq .cluster_subdomain ".preview-internal") (eq .cluster_subdomain ".nonprod-internal") }}
      annotations:
        graingercloud.com/skipValidations:  securityScan {{ end }}
    spec:
      containers:
      - name: grainger-di-demo-internal
        image: quay.io/grainger/grainger-di-httpbin:{{ .tag }}
        ports:
        - containerPort: 80
          name: "http"
        resources:
          limits:
            cpu: 1
          requests:
            cpu: 50m
        livenessProbe:
          httpGet:
            path: /anything
            port: 80
          initialDelaySeconds: 120
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /anything
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 5
      imagePullSecrets:
        - name: grainger-di-demo-internal-image-pull-secrets
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: grainger-di-demo-internal-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: grainger-di-demo-internal-deployment
  minReplicas: 3
  maxReplicas: 5
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70

---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  annotations:
    type: internal
  name: grainger-di-demo-internal-gateway
spec:
  selector:
    istio: ilbgateway
  servers:
  - hosts:
    - "{{ .hostname }}{{ .cluster_subdomain }}.graingercloud.com"
    port:
      number: 80
      name: http
      protocol: HTTP
    tls:
      httpsRedirect: true
  - hosts:
    - "{{ .hostname }}{{ .cluster_subdomain }}.graingercloud.com"
    port:
      name: https
      number: 443
      protocol: HTTPS
    tls:
      credentialName: {{ .namespace }}-internal-cert
      mode: SIMPLE
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: grainger-di-demo-internal-virtual-service
spec:
  hosts:
  - "{{ .hostname }}{{ .cluster_subdomain }}.graingercloud.com"
  gateways:
  - grainger-di-demo-internal-gateway
  http:
  - route:
    - destination:
        port:
          number: 80
        host: grainger-di-demo-internal
---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: grainger-di-demo-internal
  labels:
    app: grainger-di-demo-internal
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app: grainger-di-demo-internal