---
# Source: prometheus/templates/server/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: istio-system
  labels:
    component: "server"
    app: prometheus
    release: prometheus
spec:
  ports:
    - name: tcp-prometheus
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    component: "server"
    app: prometheus
    release: prometheus
  sessionAffinity: None
  type: "ClusterIP"
