apiVersion: v1
kind: ConfigMap
metadata:
  namespace: {{ .Release.Namespace }}
  name: pilot-envoy-config{{ .Values.version }}
  labels:
    release: {{ .Release.Name }}
data:
  envoy.yaml.tmpl: |-
    admin:
      access_log_path: /dev/null
      address:
        socket_address:
          address: 127.0.0.1
          port_value: 15000

    static_resources:
      clusters:
      - name: in.15010
        http2_protocol_options: {}
        connect_timeout: 1.000s

        hosts:
        - socket_address:
            address: 127.0.0.1
            port_value: 15010

        circuit_breakers:
          thresholds:
          - max_connections: 100000
            max_pending_requests: 100000
            max_requests: 100000
            max_retries: 3

    # TODO: telemetry using EDS
    # TODO: other pilots using EDS, load balancing
    # TODO: galley using EDS

      - name: out.galley.15019
        http2_protocol_options: {}
        connect_timeout: 1.000s
        type: STRICT_DNS

        circuit_breakers:
          thresholds:
            - max_connections: 100000
              max_pending_requests: 100000
              max_requests: 100000
              max_retries: 3
        hosts:
          - socket_address:
              address: istio-galley.{{ .Values.global.configNamespace }}
              port_value: 15019
      {{- if .Values.global.controlPlaneSecurityEnabled }}
      {{- if .Values.global.sds.enabled }}
        tls_context:
          common_tls_context:
            tls_certificate_sds_secret_configs:
            - name: default
              sds_config:
                api_config_source:
                  api_type: GRPC
                  grpc_services:
                  - google_grpc:
                      target_uri: {{ .Values.global.sds.udsPath }}
                      channel_credentials:
                        local_credentials: {}
                      call_credentials:
                      - from_plugin:
                          name: envoy.grpc_credentials.file_based_metadata
                          config:
                            header_key: istio_sds_credentials_header-bin
                            secret_data:
                              filename: /var/run/secrets/tokens/istio-token
                      credentials_factory_name: envoy.grpc_credentials.file_based_metadata
                      stat_prefix: sdsstat
            combined_validation_context:
              default_validation_context:
                verify_subject_alt_name:
                - spiffe://{{ .Values.global.trustDomain }}/ns/{{ .Values.global.configNamespace }}/sa/istio-galley-service-account
              validation_context_sds_secret_config:
                name: ROOTCA
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                    - google_grpc:
                        target_uri: {{ .Values.global.sds.udsPath }}
                        channel_credentials:
                          local_credentials: {}
                        call_credentials:
                        - from_plugin:
                            name: envoy.grpc_credentials.file_based_metadata
                            config:
                              header_key: istio_sds_credentials_header-bin
                              secret_data:
                                filename: /var/run/secrets/tokens/istio-token
                        credentials_factory_name: envoy.grpc_credentials.file_based_metadata
                        stat_prefix: sdsstat
      {{- else }}
        tls_context:
          common_tls_context:
            tls_certificates:
            - certificate_chain:
                filename: /etc/certs/cert-chain.pem
              private_key:
                filename: /etc/certs/key.pem
            validation_context:
              trusted_ca:
                filename: /etc/certs/root-cert.pem
              verify_subject_alt_name:
              - spiffe://{{ .Values.global.trustDomain }}/ns/{{ .Values.global.configNamespace }}/sa/istio-galley-service-account
      {{- end }}
      {{- end }}

      listeners:
      - name: "in.15011"
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 15011
        filter_chains:
        - filters:
          - name: envoy.http_connection_manager
            #typed_config
            #"@type": "type.googleapis.com/",
            config:
              codec_type: HTTP2
              stat_prefix: "15011"
              http2_protocol_options:
                max_concurrent_streams: 1073741824

              access_log:
              - name: envoy.file_access_log
                config:
                  path: /dev/stdout

              http_filters:
              - name: envoy.router

              route_config:
                name: "15011"

                virtual_hosts:
                - name: istio-pilot

                  domains:
                  - '*'

                  routes:
                  - match:
                      prefix: /
                    route:
                      cluster: in.15010
                      timeout: 0.000s
                    decorator:
                      operation: xDS

        {{- if .Values.global.sds.enabled }}
          tls_context:
            common_tls_context:
              alpn_protocols:
              - h2
              tls_certificate_sds_secret_configs:
              - name: default
                sds_config:
                  api_config_source:
                    api_type: GRPC
                    grpc_services:
                    - google_grpc:
                        target_uri: {{ .Values.global.sds.udsPath }}
                        channel_credentials:
                          local_credentials: {}
                        call_credentials:
                        - from_plugin:
                            name: envoy.grpc_credentials.file_based_metadata
                            config:
                              header_key: istio_sds_credentials_header-bin
                              secret_data:
                                filename: /var/run/secrets/tokens/istio-token
                        credentials_factory_name: envoy.grpc_credentials.file_based_metadata
                        stat_prefix: sdsstat
              combined_validation_context:
                default_validation_context:
                  verify_subject_alt_name: []
                validation_context_sds_secret_config:
                  name: ROOTCA
                  sds_config:
                    api_config_source:
                      api_type: GRPC
                      grpc_services:
                      - google_grpc:
                          target_uri: {{ .Values.global.sds.udsPath }}
                          channel_credentials:
                            local_credentials: {}
                          call_credentials:
                          - from_plugin:
                              name: envoy.grpc_credentials.file_based_metadata
                              config:
                                header_key: istio_sds_credentials_header-bin
                                secret_data:
                                  filename: /var/run/secrets/tokens/istio-token
                          credentials_factory_name: envoy.grpc_credentials.file_based_metadata
                          stat_prefix: sdsstat
            require_client_certificate: true
        {{- else }}
          tls_context:
            common_tls_context:
              alpn_protocols:
              - h2
              tls_certificates:
              - certificate_chain:
                  filename: /etc/certs/cert-chain.pem
                private_key:
                  filename: /etc/certs/key.pem
              validation_context:
                trusted_ca:
                  filename: /etc/certs/root-cert.pem
            require_client_certificate: true
        {{- end }}


      # Manual 'whitebox' mode
      - name: "local.15019"
        address:
          socket_address:
            address: 127.0.0.1
            port_value: 15019
        filter_chains:
          - filters:
              - name: envoy.http_connection_manager
                config:
                  codec_type: HTTP2
                  stat_prefix: "15019"
                  http2_protocol_options:
                    max_concurrent_streams: 1073741824

                  access_log:
                    - name: envoy.file_access_log
                      config:
                        path: /dev/stdout

                  http_filters:
                    - name: envoy.router

                  route_config:
                    name: "15019"

                    virtual_hosts:
                      - name: istio-galley

                        domains:
                          - '*'

                        routes:
                          - match:
                              prefix: /
                            route:
                              cluster: out.galley.15019
                              timeout: 0.000s

---

