---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook
  namespace: blue-local
  labels:
    app.kubernetes.io/name: guestbook
    app.kubernetes.io/component: guestbook-ui
    app.kubernetes.io/part-of: guestbook
    app.kubernetes.io/environment: local
