---
apiVersion: v1
kind: Service
metadata:
  name: influxdb
  labels:
    app: influxdb
  namespace: monitoring
spec:
  selector:
    app: influxdb
  ports:
  - name: http
    port: 8083
    targetPort: http
  - name: api
    port: 8086
    targetPort: api

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influxdb
  labels:
    app: influxdb
  namespace: monitoring
spec:
  selector:
    matchLabels:
      app: influxdb
  replicas: 1
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      serviceAccountName: influxdb
      containers:
        - name: influxdb
          image: k8s.gcr.io/heapster-influxdb-amd64:v1.3.3
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 8083
          - name: api
            containerPort: 8086
          resources:
            limits:
              cpu: 100m
              memory: 500Mi
          volumeMounts:
          - name: influxdb-persistent-storage
            mountPath: /data
      volumes:
      - name: influxdb-persistent-storage
        emptyDir: {}