---
apiVersion: v1
kind: Service
metadata:
  name: heapster
  labels:
    app: heapster
    task: monitoring
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: Heapster
  namespace: kube-system
spec:
  selector:
    app: heapster
  ports:
  - port: 80
    targetPort: http

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: heapster
  labels:
    app: heapster
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: heapster
  replicas: 1
  template:
    metadata:
      labels:
        app: heapster
        task: monitoring
    spec:
      serviceAccountName: heapster
      containers:
      - name: heapster
        image: k8s.gcr.io/heapster-amd64:v1.5.3
        imagePullPolicy: IfNotPresent
        command:
        - /heapster
        - --source=kubernetes.summary_api:''
        - --sink=influxdb:http://influxdb.monitoring:8086
        ports:
        - name: api
          containerPort: 9090
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /healthz
            port: api
            scheme: HTTP
          initialDelaySeconds: 180
          timeoutSeconds: 5
        resources:
          limits:
            cpu: 200m
            memory: 128Mi
