---
apiVersion: v1
kind: Service
metadata:
  name: ratings
  namespace: bookinfo
  labels:
    app: ratings
    service: ratings
spec:
  ports:
  - port: 9080
    name: ratings-http
  selector:
    app: ratings

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ratings
  namespace: bookinfo
  labels:
    app: ratings
    service: ratings

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ratings
  labels:
    app: ratings
    version: "v1.16.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ratings
      version: "v1.16.2"
  template:
    metadata:
      labels:
        app: ratings
        version: "v1.16.2"
    spec:
      serviceAccountName: ratings
      containers:
        - name: ratings
          image: docker.io/istio/examples-bookinfo-ratings-v2:1.16.2
          imagePullPolicy: IfNotPresent
          env:
            - name: MONGO_DB_URL
              value: mongodb://mongodb:27017/test
          ports:
          - containerPort: 9080
