---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  namespace: bookinfo
  labels:
    app: mongodb
spec:
  ports:
  - port: 27017
    name: mongo
  selector:
    app: mongodb

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: bookinfo
  labels:
    app: mongodb
    version: "v1.16.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
      version: "v1.16.2"
  template:
    metadata:
      labels:
        app: mongodb
        version: "v1.16.2"
    spec:
      containers:
      - name: mongodb 
        image: docker.io/istio/examples-bookinfo-mongodb:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: data-db
          mountPath: /data/db
      volumes:
      - name: data-db
        emptyDir:
