---
apiVersion: v1
kind: Service
metadata:
  name: kibana
  labels:
    app: kibana
  namespace: kube-system
spec:
  selector:
    app: kibana
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: NodePort

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana
  labels:
    app: kibana
  namespace: kube-system
spec:
  selector:
    matchLabels:
     app: kibana
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: kibana
    spec:
      serviceAccountName: kibana
      containers:
      - name: kibana
        image: docker.elastic.co/kibana/kibana-oss:6.6.0
        imagePullPolicy: IfNotPresent
        env:
        - name: CLUSTER_NAME
          value: "docker-cluster"
        ports:
        - name: http
          containerPort: 5601
          protocol: TCP
        resources:
          limits:
            cpu: 1000m
          requests:
            cpu: 100m
        volumeMounts:
        - name: config
          mountPath: /usr/share/kibana/kibana.yml
          subPath: kibana.yml
      volumes:
      - name: config
        configMap:
          name: kibana-configmap