---
# Source: metrics-server/templates/metrics-server-serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metrics-server
  namespace: kube-system
  labels:
    app: metrics-server
    chart: metrics-server-2.5.0
    release: metrics-server
    heritage: Tiller