---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: redis
  namespace: blue-local
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/component: guestbook-redis
    app.kubernetes.io/part-of: guestbook
    app.kubernetes.io/environment: local
