---
apiVersion: v1
kind: Service
metadata:
  name: redis-master
  namespace: blue-local
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: guestbook-redis
    app.kubernetes.io/part-of: guestbook
    app.kubernetes.io/environment: local
    app: redis
    version: v1.0.0
    role: master
spec:
  ports:
  - port: 6379
    targetPort: 6379
    name: tcp-redis
  selector:
    app: redis
    role: master
    version: v1.0.0
