---
apiVersion: v1
kind: Service
metadata:
  name: reviews
  namespace: bookinfo
  labels:
    app: reviews
    service: reviews
spec:
  ports:
  - port: 9080
    name: reviews-http
  selector:
    app: reviews

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reviews
  namespace: bookinfo
  labels:
    account: reviews

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reviews
  namespace: bookinfo
  labels:
    app: reviews
    version: "v1.16.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reviews
      version: "v1.16.2"
  template:
    metadata:
      labels:
        app: reviews
        version: "v1.16.2"
    spec:
      serviceAccountName: reviews
      containers:
      - name: reviews
        image: docker.io/istio/examples-bookinfo-reviews-v2:1.16.2
        imagePullPolicy: IfNotPresent
        env:
        - name: LOG_DIR
          value: "/tmp/logs"
        ports:
        - containerPort: 9080
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: wlp-output
          mountPath: /opt/ibm/wlp/output
      volumes:
      - name: wlp-output
        emptyDir: {}
      - name: tmp
        emptyDir: {}
