apiVersion: v1
kind: Secret
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
type: Opaque
data:
  # username: user
  # passphrase: kiali
  username: "dXNlcg=="
  passphrase: "a2lhbGk="