run:
  deadline: 2m

linters:
  disable-all: true
  enable:
    - gofmt
    - goimports
    - golint
    - gosimple
    - gocyclo
    - ineffassign
    - misspell
    - gocritic
    - govet

linters-settings:
  goimports:
local-prefixes: k8s.io/kube-state-metrics