---
apiVersion: v1
kind: Service
metadata:
  name: details
  namespace: bookinfo
  labels:
    app: details
    service: details
spec:
  ports:
  - port: 9080
    name: details-http
  selector:
    app: details

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: details
  namespace: bookinfo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: details
  namespace: bookinfo
  labels:
    app: details
    version: "v1.16.2"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: details
      version: "v1.16.2"
  template:
    metadata:
      labels:
        app: details
        version: "v1.16.2"
    spec:
      serviceAccountName: details
      containers:
      - name: details
        image: docker.io/istio/examples-bookinfo-details-v1:1.16.2
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 9080
