---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cerebro
  namespace: monitoring

---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cerebro
  namespace: monitoring
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: cerebro
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cerebro
subjects:
- kind: ServiceAccount
  name: cerebro
  namespace: monitoring