---
# Source: istio/charts/kiali/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kiali
  namespace: istio-system
  labels:
    app: kiali
data:
  config.yaml: |
    server:
      port: 20001
    external_services:
      jaeger:
        url: http://10.102.141.229:80
      grafana:
        url: http://10.101.58.241:3000
