---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-slave
  namespace: blue-local
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: v1.0.0
    app.kubernetes.io/component: guestbook-redis
    app.kubernetes.io/part-of: guestbook
    app.kubernetes.io/environment: local
    app: redis
    role: slave
    version: v1.0.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app: redis
      role: slave
      version: v1.0.0
  template:
    metadata:
      labels:
        app: redis
        role: slave
        version: v1.0.0
    spec:
      serviceAccountName: redis
      containers:
      - image: k8s.gcr.io/redis-slave:v2
        imagePullPolicy: IfNotPresent
        name: redis-slave
        ports:
        - name: tcp-redis
          containerPort: 6379
